comment: false
ignore:
  - "addins.R"
  - "ee_clean.R"
  - "ee_install.R"
  - "zzz.R"

coverage:
  status:
    patch:
      default:
        target: 0
        threshold: 95
    project:
      default:
        target: 70
        threshold: 95